const elements = [
  { number: 1, symbol: "H", name: "Hydrogen", category: "nonmetal", group: 1, period: 1, atomicMass: 1.008, normalState: "💨Gas" },
  { number: 2, symbol: "He", name: "Helium", category: "noble 💨Gas", group: 18, period: 1, atomicMass: 4.0026, normalState: "💨Gas" },
  { number: 3, symbol: "Li", name: "Lithium", category: "alkali metal", group: 1, period: 2, atomicMass: 6.94, normalState: "🧱Solid" },
  { number: 4, symbol: "Be", name: "Beryllium", category: "alkaline earth metal", group: 2, period: 2, atomicMass: 9.0122, normalState: "🧱Solid" },
  { number: 5, symbol: "B", name: "Boron", category: "metalloid", group: 13, period: 2, atomicMass: 10.81, normalState: "🧱Solid" },
  { number: 6, symbol: "C", name: "Carbon", category: "nonmetal", group: 14, period: 2, atomicMass: 12.011, normalState: "🧱Solid" },
  { number: 7, symbol: "N", name: "Nitrogen", category: "nonmetal", group: 15, period: 2, atomicMass: 14.007, normalState: "💨Gas" },
  { number: 8, symbol: "O", name: "Oxygen", category: "nonmetal", group: 16, period: 2, atomicMass: 15.999, normalState: "💨Gas" },
  { number: 9, symbol: "F", name: "Fluorine", category: "halogen", group: 17, period: 2, atomicMass: 18.998, normalState: "💨Gas" },
  { number: 10, symbol: "Ne", name: "Neon", category: "noble 💨Gas", group: 18, period: 2, atomicMass: 20.180, normalState: "💨Gas" },
  { number: 11, symbol: "Na", name: "Sodium", category: "alkali metal", group: 1, period: 3, atomicMass: 22.990, normalState: "🧱Solid" },
  { number: 12, symbol: "Mg", name: "Magnesium", category: "alkaline earth metal", group: 2, period: 3, atomicMass: 24.305, normalState: "🧱Solid" },
  { number: 13, symbol: "Al", name: "Aluminium", category: "post-transition metal", group: 13, period: 3, atomicMass: 26.982, normalState: "🧱Solid" },
  { number: 14, symbol: "Si", name: "Silicon", category: "metalloid", group: 14, period: 3, atomicMass: 28.085, normalState: "🧱Solid" },
  { number: 15, symbol: "P", name: "Phosphorus", category: "nonmetal", group: 15, period: 3, atomicMass: 30.974, normalState: "🧱Solid" },
  { number: 16, symbol: "S", name: "Sulfur", category: "nonmetal", group: 16, period: 3, atomicMass: 32.06, normalState: "🧱Solid" },
  { number: 17, symbol: "Cl", name: "Chlorine", category: "halogen", group: 17, period: 3, atomicMass: 35.45, normalState: "💨Gas" },
  { number: 18, symbol: "Ar", name: "Argon", category: "noble 💨Gas", group: 18, period: 3, atomicMass: 39.948, normalState: "💨Gas" },
  { number: 19, symbol: "K", name: "Potassium", category: "alkali metal", group: 1, period: 4, atomicMass: 39.098, normalState: "🧱Solid" },
  { number: 20, symbol: "Ca", name: "Calcium", category: "alkaline earth metal", group: 2, period: 4, atomicMass: 40.078, normalState: "🧱Solid" },
  { number: 21, symbol: "Sc", name: "Scandium", category: "transition metal", group: 3, period: 4, atomicMass: 44.956, normalState: "🧱Solid" },
  { number: 22, symbol: "Ti", name: "Titanium", category: "transition metal", group: 4, period: 4, atomicMass: 47.867, normalState: "🧱Solid" },
  { number: 23, symbol: "V", name: "Vanadium", category: "transition metal", group: 5, period: 4, atomicMass: 50.942, normalState: "🧱Solid" },
  { number: 24, symbol: "Cr", name: "Chromium", category: "transition metal", group: 6, period: 4, atomicMass: 51.996, normalState: "🧱Solid" },
  { number: 25, symbol: "Mn", name: "Manganese", category: "transition metal", group: 7, period: 4, atomicMass: 54.938, normalState: "🧱Solid" },
  { number: 26, symbol: "Fe", name: "Iron", category: "transition metal", group: 8, period: 4, atomicMass: 55.845, normalState: "🧱Solid" },
  { number: 27, symbol: "Co", name: "Cobalt", category: "transition metal", group: 9, period: 4, atomicMass: 58.933, normalState: "🧱Solid" },
  { number: 28, symbol: "Ni", name: "Nickel", category: "transition metal", group: 10, period: 4, atomicMass: 58.693, normalState: "🧱Solid" },
  { number: 29, symbol: "Cu", name: "Copper", category: "transition metal", group: 11, period: 4, atomicMass: 63.546, normalState: "🧱Solid" },
  { number: 30, symbol: "Zn", name: "Zinc", category: "transition metal", group: 12, period: 4, atomicMass: 65.38, normalState: "🧱Solid" },
  { number: 31, symbol: "Ga", name: "Gallium", category: "post-transition metal", group: 13, period: 4, atomicMass: 69.723, normalState: "🧱Solid" },
  { number: 32, symbol: "Ge", name: "Germanium", category: "metalloid", group: 14, period: 4, atomicMass: 72.63, normalState: "🧱Solid" },
  { number: 33, symbol: "As", name: "Arsenic", category: "metalloid", group: 15, period: 4, atomicMass: 74.922, normalState: "🧱Solid" },
  { number: 34, symbol: "Se", name: "Selenium", category: "polyatomic nonmetal", group: 16, period: 4, atomicMass: 78.971, normalState: "🧱Solid" },
  { number: 35, symbol: "Br", name: "Bromine", category: "halogen", group: 17, period: 4, atomicMass: 79.904, normalState: "💧Liquid" },
  { number: 36, symbol: "Kr", name: "Krypton", category: "noble 💨Gas", group: 18, period: 4, atomicMass: 83.798, normalState: "💨Gas" },
  { number: 37, symbol: "Rb", name: "Rubidium", category: "alkali metal", group: 1, period: 5, atomicMass: 85.468, normalState: "🧱Solid" },
  { number: 38, symbol: "Sr", name: "Strontium", category: "alkaline earth metal", group: 2, period: 5, atomicMass: 87.62, normalState: "🧱Solid" },
  { number: 39, symbol: "Y", name: "Yttrium", category: "transition metal", group: 3, period: 5, atomicMass: 88.906, normalState: "🧱Solid" },
  { number: 40, symbol: "Zr", name: "Zirconium", category: "transition metal", group: 4, period: 5, atomicMass: 91.224, normalState: "🧱Solid" },
  { number: 41, symbol: "Nb", name: "Niobium", category: "transition metal", group: 5, period: 5, atomicMass: 92.906, normalState: "🧱Solid" },
  { number: 42, symbol: "Mo", name: "Molybdenum", category: "transition metal", group: 6, period: 5, atomicMass: 95.95, normalState: "🧱Solid" },
  { number: 43, symbol: "Tc", name: "Technetium", category: "transition metal", group: 7, period: 5, atomicMass: 98, normalState: "🧱Solid" },
  { number: 44, symbol: "Ru", name: "Ruthenium", category: "transition metal", group: 8, period: 5, atomicMass: 101.07, normalState: "🧱Solid" },
  { number: 45, symbol: "Rh", name: "Rhodium", category: "transition metal", group: 9, period: 5, atomicMass: 102.91, normalState: "🧱Solid" },
  { number: 46, symbol: "Pd", name: "Palladium", category: "transition metal", group: 10, period: 5, atomicMass: 106.42, normalState: "🧱Solid" },
  { number: 47, symbol: "Ag", name: "Silver", category: "transition metal", group: 11, period: 5, atomicMass: 107.87, normalState: "🧱Solid" },
  { number: 48, symbol: "Cd", name: "Cadmium", category: "transition metal", group: 12, period: 5, atomicMass: 112.41, normalState: "🧱Solid" },
  { number: 49, symbol: "In", name: "Indium", category: "post-transition metal", group: 13, period: 5, atomicMass: 114.82, normalState: "🧱Solid" },
  { number: 50, symbol: "Sn", name: "Tin", category: "post-transition metal", group: 14, period: 5, atomicMass: 118.71, normalState: "🧱Solid" },
  { number: 51, symbol: "Sb", name: "Antimony", category: "metalloid", group: 15, period: 5, atomicMass: 121.76, normalState: "🧱Solid" },
  { number: 52, symbol: "Te", name: "Tellurium", category: "metalloid", group: 16, period: 5, atomicMass: 127.60, normalState: "🧱Solid" },
  { number: 53, symbol: "I", name: "Iodine", category: "halogen", group: 17, period: 5, atomicMass: 126.90, normalState: "🧱Solid" },
  { number: 54, symbol: "Xe", name: "Xenon", category: "noble 💨Gas", group: 18, period: 5, atomicMass: 131.29, normalState: "💨Gas" },
  { number: 55, symbol: "Cs", name: "Cesium", category: "alkali metal", group: 1, period: 6, atomicMass: 132.91, normalState: "🧱Solid" },
  { number: 56, symbol: "Ba", name: "Barium", category: "alkaline earth metal", group: 2, period: 6, atomicMass: 137.33, normalState: "🧱Solid" },
  { number: 57, symbol: "La", name: "Lanthanum", category: "lanthanide", group: 3, period: 6, atomicMass: 138.91, normalState: "🧱Solid" },
  { number: 58, symbol: "Ce", name: "Cerium", category: "lanthanide", group: 3, period: 6, atomicMass: 140.12, normalState: "🧱Solid" },
  { number: 59, symbol: "Pr", name: "Praseodymium", category: "lanthanide", group: 3, period: 6, atomicMass: 140.91, normalState: "🧱Solid" },
  { number: 60, symbol: "Nd", name: "Neodymium", category: "lanthanide", group: 3, period: 6, atomicMass: 144.24, normalState: "🧱Solid" },
  { number: 61, symbol: "Pm", name: "Promethium", category: "lanthanide", group: 3, period: 6, atomicMass: 145, normalState: "🧱Solid" },
  { number: 62, symbol: "Sm", name: "Samarium", category: "lanthanide", group: 3, period: 6, atomicMass: 150.36, normalState: "🧱Solid" },
  { number: 63, symbol: "Eu", name: "Europium", category: "lanthanide", group: 3, period: 6, atomicMass: 151.98, normalState: "🧱Solid" },
  { number: 64, symbol: "Gd", name: "Gadolinium", category: "lanthanide", group: 3, period: 6, atomicMass: 157.25, normalState: "🧱Solid" },
  { number: 65, symbol: "Tb", name: "Terbium", category: "lanthanide", group: 3, period: 6, atomicMass: 158.93, normalState: "🧱Solid" },
  { number: 66, symbol: "Dy", name: "Dysprosium", category: "lanthanide", group: 3, period: 6, atomicMass: 162.50, normalState: "🧱Solid" },
  { number: 67, symbol: "Ho", name: "Holmium", category: "lanthanide", group: 3, period: 6, atomicMass: 164.93, normalState: "🧱Solid" },
  { number: 68, symbol: "Er", name: "Erbium", category: "lanthanide", group: 3, period: 6, atomicMass: 167.26, normalState: "🧱Solid" },
  { number: 69, symbol: "Tm", name: "Thulium", category: "lanthanide", group: 3, period: 6, atomicMass: 168.93, normalState: "🧱Solid" },
  { number: 70, symbol: "Yb", name: "Ytterbium", category: "lanthanide", group: 3, period: 6, atomicMass: 173.05, normalState: "🧱Solid" },
  { number: 71, symbol: "Lu", name: "Lutetium", category: "lanthanide", group: 3, period: 6, atomicMass: 174.97, normalState: "🧱Solid" },
  { number: 72, symbol: "Hf", name: "Hafnium", category: "transition metal", group: 4, period: 6, atomicMass: 178.49, normalState: "🧱Solid" },
  { number: 73, symbol: "Ta", name: "Tantalum", category: "transition metal", group: 5, period: 6, atomicMass: 180.95, normalState: "🧱Solid" },
  { number: 74, symbol: "W", name: "Tungsten", category: "transition metal", group: 6, period: 6, atomicMass: 183.84, normalState: "🧱Solid" },
  { number: 75, symbol: "Re", name: "Rhenium", category: "transition metal", group: 7, period: 6, atomicMass: 186.21, normalState: "🧱Solid" },
  { number: 76, symbol: "Os", name: "Osmium", category: "transition metal", group: 8, period: 6, atomicMass: 190.23, normalState: "🧱Solid" },
  { number: 77, symbol: "Ir", name: "Iridium", category: "transition metal", group: 9, period: 6, atomicMass: 192.22, normalState: "🧱Solid" },
  { number: 78, symbol: "Pt", name: "Platinum", category: "transition metal", group: 10, period: 6, atomicMass: 195.08, normalState: "🧱Solid" },
  { number: 79, symbol: "Au", name: "Gold", category: "transition metal", group: 11, period: 6, atomicMass: 196.97, normalState: "🧱Solid" },
  { number: 80, symbol: "Hg", name: "Mercury", category: "transition metal", group: 12, period: 6, atomicMass: 200.59, normalState: "💧Liquid" },
  { number: 81, symbol: "Tl", name: "Thallium", category: "post-transition metal", group: 13, period: 6, atomicMass: 204.38, normalState: "🧱Solid" },
  { number: 82, symbol: "Pb", name: "Lead", category: "post-transition metal", group: 14, period: 6, atomicMass: 207.2, normalState: "🧱Solid" },
  { number: 83, symbol: "Bi", name: "Bismuth", category: "post-transition metal", group: 15, period: 6, atomicMass: 208.98, normalState: "🧱Solid" },
  { number: 84, symbol: "Po", name: "Polonium", category: "post-transition metal", group: 16, period: 6, atomicMass: 209, normalState: "🧱Solid" },
  { number: 85, symbol: "At", name: "Astatine", category: "metalloid", group: 17, period: 6, atomicMass: 210, normalState: "🧱Solid" },
  { number: 86, symbol: "Rn", name: "Radon", category: "noble 💨Gas", group: 18, period: 6, atomicMass: 222, normalState: "💨Gas" },
  { number: 87, symbol: "Fr", name: "Francium", category: "alkali metal", group: 1, period: 7, atomicMass: 223, normalState: "🧱Solid" },
  { number: 88, symbol: "Ra", name: "Radium", category: "alkaline earth metal", group: 2, period: 7, atomicMass: 226, normalState: "🧱Solid" },
  { number: 89, symbol: "Ac", name: "Actinium", category: "actinide", group: 3, period: 7, atomicMass: 227, normalState: "🧱Solid" },
  { number: 90, symbol: "Th", name: "Thorium", category: "actinide", group: 3, period: 7, atomicMass: 232.04, normalState: "🧱Solid" },
  { number: 91, symbol: "Pa", name: "Protactinium", category: "actinide", group: 3, period: 7, atomicMass: 231.04, normalState: "🧱Solid" },
  { number: 92, symbol: "U", name: "Uranium", category: "actinide", group: 3, period: 7, atomicMass: 238.03, normalState: "🧱Solid" },
  { number: 93, symbol: "Np", name: "Neptunium", category: "actinide", group: 3, period: 7, atomicMass: 237, normalState: "🧱Solid" },
  { number: 94, symbol: "Pu", name: "Plutonium", category: "actinide", group: 3, period: 7, atomicMass: 244, normalState: "🧱Solid" },
  { number: 95, symbol: "Am", name: "Americium", category: "actinide", group: 3, period: 7, atomicMass: 243, normalState: "🧱Solid" },
  { number: 96, symbol: "Cm", name: "Curium", category: "actinide", group: 3, period: 7, atomicMass: 247, normalState: "🧱Solid" },
  { number: 97, symbol: "Bk", name: "Berkelium", category: "actinide", group: 3, period: 7, atomicMass: 247, normalState: "🧱Solid" },
  { number: 98, symbol: "Cf", name: "Californium", category: "actinide", group: 3, period: 7, atomicMass: 251, normalState: "🧱Solid" },
  { number: 99, symbol: "Es", name: "Einsteinium", category: "actinide", group: 3, period: 7, atomicMass: 252, normalState: "🧱Solid" },
  { number: 100, symbol: "Fm", name: "Fermium", category: "actinide", group: 3, period: 7, atomicMass: 257, normalState: "🧱Solid" },
  { number: 101, symbol: "Md", name: "Mendelevium", category: "actinide", group: 3, period: 7, atomicMass: 258, normalState: "🧱Solid" },
  { number: 102, symbol: "No", name: "Nobelium", category: "actinide", group: 3, period: 7, atomicMass: 259, normalState: "🧱Solid" },
  { number: 103, symbol: "Lr", name: "Lawrencium", category: "actinide", group: 3, period: 7, atomicMass: 266, normalState: "🧱Solid" },
  { number: 104, symbol: "Rf", name: "Rutherfordium", category: "transition metal", group: 4, period: 7, atomicMass: 267, normalState: "unknown" },
  { number: 105, symbol: "Db", name: "Dubnium", category: "transition metal", group: 5, period: 7, atomicMass: 270, normalState: "unknown" },
  { number: 106, symbol: "Sg", name: "Seaborgium", category: "transition metal", group: 6, period: 7, atomicMass: 271, normalState: "unknown" },
  { number: 107, symbol: "Bh", name: "Bohrium", category: "transition metal", group: 7, period: 7, atomicMass: 270, normalState: "unknown" },
  { number: 108, symbol: "Hs", name: "Hassium", category: "transition metal", group: 8, period: 7, atomicMass: 277, normalState: "unknown" },
  { number: 109, symbol: "Mt", name: "Meitnerium", category: "unknown, probably transition metal", group: 9, period: 7, atomicMass: 278, normalState: "unknown" },
  { number: 110, symbol: "Ds", name: "Darmstadtium", category: "unknown, probably transition metal", group: 10, period: 7, atomicMass: 281, normalState: "unknown" },
  { number: 111, symbol: "Rg", name: "Roentgenium", category: "unknown, probably transition metal", group: 11, period: 7, atomicMass: 282, normalState: "unknown" },
  { number: 112, symbol: "Cn", name: "Copernicium", category: "transition metal", group: 12, period: 7, atomicMass: 285, normalState: "unknown" },
  { number: 113, symbol: "Nh", name: "Nihonium", category: "unknown, probably transition metal", group: 13, period: 7, atomicMass: 286, normalState: "unknown" },
  { number: 114, symbol: "Fl", name: "Flerovium", category: "post-transition metal", group: 14, period: 7, atomicMass: 289, normalState: "unknown" },
  { number: 115, symbol: "Mc", name: "Moscovium", category: "unknown, probably post-transition metal", group: 15, period: 7, atomicMass: 290, normalState: "unknown" },
  { number: 116, symbol: "Lv", name: "Livermorium", category: "unknown, probably post-transition metal", group: 16, period: 7, atomicMass: 293, normalState: "unknown" },
  { number: 117, symbol: "Ts", name: "Tennessine", category: "unknown, probably metalloid", group: 17, period: 7, atomicMass: 294, normalState: "unknown" },
  { number: 118, symbol: "Og", name: "Oganesson", category: "noble 💨Gas", group: 18, period: 7, atomicMass: 294, normalState: "unknown" }
];
export{ elements }